version: "3"

services:
  frontier:
    build:
      context: .
      dockerfile: frontier/Dockerfile
    image: frontier:latest
    ports:
      - "8080:8080"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    image: worker:latest
    environment:
      FRONTIER_URL: "http://frontier:8080"
    depends_on:
      - frontier
    scale: 3
    restart: unless-stopped
